development:
  adapter: postgresql
  database: webform_embed_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: webform_embed_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: webform_embed_production
  pool: 5
  timeout: 5000